library("deSolve")
library("rgl")
library("plyr")
devtools::load_all(".")
r <- Params()
plot(r)
sim <- Sim(r)
plot(sim)

persp3d(sim@t, sim@w, sim@p[, , 1], col = "lightblue",
        xlab="t", ylab="w", zlab="p")

#Our input p0 is a random pertubation of the solution
#generated by the code at the start
p0 <- matrix(r@psiBar, nrow=sim@N, ncol = 2)#*(1+0.05*runif(Ns*(N+1)))
Nu0 <- r@NuBar#*(1+0.05*runif(1))

# Some alternatives
p0 <- matrix(5*exp(-100*(sim@w - 0.6)^2), nrow=sim@N, ncol=sim@Ns)
#p0[ ,1] <- p0[(N+1):1,1]
#plot(w, p0[ ,1])

sim <- Sim(r, p0=p0)

plot(sim@w, sim@p[1, , 1], type="l", xlab="w", ylab="p_1(t=0)")
plot(sim@w, sim@p[5, , 1], type="l", xlab="w", ylab="p_1(t=dt)")
persp3d(sim@t, sim@w, sim@p[, , 1], col = "lightblue",
        xlab="t", ylab="w", zlab="p")

persp3d(sim@x, sim@xs, sim@p[sim@Nt, , ], col = "lightblue",
        xlab="x", ylab="x*", zlab="p",
        main="")

plot(sim@xa, community_spectrum(sim@p[sim@Nt, , ], sim), type="l")

plot(sim@t, sim@Nu, type="l", ylab="N")

for (ti in 1:sim@Nt) {
    persp3d(sim@x, sim@xs, sim@p[ti, , ], col = "lightblue", xlab="x", ylab="x*")
    Sys.sleep(0.5)
}

pcpt <- matrix(nrow = length(t), ncol = Na)
for (ti in 1:length(t)) {
    pcpt[ti,] <- community_spectrum(psit[ti,1:N,])
}
persp3d(t, xa, pcpt, col = "lightblue")
