library("rgl")
source("multi-species/steady_state.R")
source("multi-species/lib.R")
source("multi-species/params.R")

r <- setParams()
plot(r)

#Our input p0 is a random pertubation of the solution
#generated by the code at the start
p0 <- psi#*(1+0.05*runif(Ns*(N+1)))
Nu0 <- Nu#*(1+0.05*runif(1))

# Some alternatives
#p0[ ,1] <- 5*exp(-100*(w - 0.6)^2)
#p0[ ,1] <- p0[(N+1):1,1]
#plot(w, p0[ ,1])

sim <- simulate(r)
psit <- sim@p
Nut <- sim@Nu

persp3d(t, w, psit[,,1], col = "lightblue")
plot(t, Nut, type="l", ylab="N")

pcpt <- matrix(nrow = length(t), ncol = Na)
for (ti in 1:length(t)) {
    pcpt[ti,] <- community_spectrum(psit[ti,1:N,])
}
persp3d(t, xa, pcpt, col = "lightblue")
